### ISSUE TITLE
Can't add file with ASP.NET project

### ISSUE THREAD

**Issue by OkayX6** [fsprojects/FSharpCommunityTemplates#100]
Hi,

I am Windows 10 Pro, and this problem reproduces in both Visual Studio 2013 and 2015:
My window is empty, thus I can't create a file through the interface...

![image](https://cloud.githubusercontent.com/assets/1169339/10034976/dfb34ddc-6195-11e5-9873-0900f5d5236d.png)

Hasn't it already been encountered before?

Thanks
Denis

**Comment by panesofglass** [comment]
Did you try https://visualstudiogallery.msdn.microsoft.com/f1dae7fe-1ecc-4f1b-86b5-32a2970d012a? Not sure if that works with VS2015, though.

**Comment by OkayX6** [comment]
Yeah, I have installed it. I really think it's because of Windows 10 (recently installed), I am sure it worked before I migrate but I am not 100% sure.

**Comment by panesofglass** [comment]
One of my coworkers recently saw this same issue after installing the SQL tools. I am not sure if he ever resolved it. I think the root problem is somewhere in the F# project system, unfortunately.

**Comment by KevinRansom** [comment]
@OkayX6 

Hmmm!!! that's not great at all.  I believe it is actually a bug in the VS Extensibility Platform

You should at least see three sub headings: Data, General and Code.  in fact some people also see an FSharp, with Code,Data and General below that.  Which is the actual design.  Lincoln spent a lot of effort trying to get the designed outcome,

Can you do an experiment for me please:
1. In file explore open the folder, where X is the drive you installed Visual studio 
X:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions
2. Search for **ItemTemplates**, there may be several hits, open file location on each hit until you see one with a subfolder named **FSharp**
3. Go into that folder and create a subfolder also called fsharp, then move code,data and General into the new sub folder.

on my machine that creates a new category called FSharp with code, data and General Below that.
Let me know what happens on your machine?

That is a pretty fragile fix, any time you install F# it will go away.  I can fix our installer to always add that extra folder, however, on most machines that will give a display of fsharp\fsharp\data.  Which I suppose is not such a bad thing.  I will get in touch with Viktor who I think owns the group that owns that code and see if we can figure out what the correct fix is.

Please let me know how the experiment goes

**Comment by KevinRansom** [comment]
On twitter apparently there is a fix:  
![untitled](https://cloud.githubusercontent.com/assets/5175830/10063220/31bf6cde-6220-11e5-8ffe-4058ef6d12c9.png)

**Comment by OkayX6** [comment]
Yeah, it's cool, we can close it for now, but how can we improve things? (other than adding an entry to a FAQ, which I can do).

@KevinRansom I guess you don't want me to run the experiment anymore. Just out of curiosity, are you still planning to make a reasonable fix for this? This is rather fragile.

**Comment by panesofglass** [comment]
This will likely be fixed by moving to the new project extensibility model. See https://github.com/Microsoft/visualfsharp/issues/496. @KevinRansom?

Also, the web project templates were submitted as a PR to the Visual F# Tools about a year ago. I think @KevinRansom is still working on getting that PR worked into the VFT repo. Once that is done, I'm hoping these sorts of issues will be resolved.

**Comment by piers7** [comment]
I had this issue too (VS 2015, Win7). It all worked when I originally installed, but somewhere along the line I lost the templates. Running as admin and building didn't seem to fix it (at the time), but after I copied the templates into the 'fsharp' subfolder I then had the templates _twice_ and was able to remove one set and it still work. So maybe admin did fix it after all.
(Note that prior to that I checked the registry and all the bits seemed to be in the right place as per http://bloggemdano.blogspot.com.au/2013/11/adding-new-items-to-pure-f-aspnet.html so pretty confused all round)
